
/* automatically generated by cm_config.exe; do not change */
/* (c) Renato Jorge Caleira Nunes */


  /* 1 s timers */

  // ++WATER_PLANT_timer;

  /*++MMM_timer;*/


/* automatically generated by cm_config.exe; do not change */
/* (c) Renato Jorge Caleira Nunes */

