
/* automatically generated by cm_config.exe; do not change */
/* (c) Renato Jorge Caleira Nunes */


  /* 10 ms timers */

  COM_timer++;
  SYS_led_timer++;
  //BYTE_timer++;


/* automatically generated by cm_config.exe; do not change */
/* (c) Renato Jorge Caleira Nunes */
