
/* automatically generated by cm_config.exe; do not change */
/* (c) Renato Jorge Caleira Nunes */


  /* 10 ms timers */

  //COM_timer++;
  //BYTE_timer++;
  //SYS_led_timer++;
  //WATER_timer++;



/* automatically generated by cm_config.exe; do not change */
/* (c) Renato Jorge Caleira Nunes */
